custom:
  - https://www.paypal.com/donate/?hosted_button_id=NGEL6AB5A6KNL
  - https://venmo.com/empathetech
  - https://cash.app/$empathetech
  - https://www.buymeacoffee.com/empathetech
ko_fi: empathetech
patreon: empathetech